// Code generated by protoc-gen-go.
// source: file.proto
// DO NOT EDIT!

/*
Package file is a generated protocol buffer package.

It is generated from these files:
	file.proto

It has these top-level messages:
	File
*/
package file

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type File_Action int32

const (
	File_ADD    File_Action = 0
	File_UPDATE File_Action = 1
	File_DELETE File_Action = 2
)

var File_Action_name = map[int32]string{
	0: "ADD",
	1: "UPDATE",
	2: "DELETE",
}
var File_Action_value = map[string]int32{
	"ADD":    0,
	"UPDATE": 1,
	"DELETE": 2,
}

func (x File_Action) Enum() *File_Action {
	p := new(File_Action)
	*p = x
	return p
}
func (x File_Action) String() string {
	return proto.EnumName(File_Action_name, int32(x))
}
func (x *File_Action) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(File_Action_value, data, "File_Action")
	if err != nil {
		return err
	}
	*x = File_Action(value)
	return nil
}
func (File_Action) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type File struct {
	Path             *string      `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Mode             *uint32      `protobuf:"varint,2,req,name=mode" json:"mode,omitempty"`
	Payload          []byte       `protobuf:"bytes,3,req,name=payload" json:"payload,omitempty"`
	Action           *File_Action `protobuf:"varint,4,req,name=action,enum=File_Action" json:"action,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *File) Reset()                    { *m = File{} }
func (m *File) String() string            { return proto.CompactTextString(m) }
func (*File) ProtoMessage()               {}
func (*File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *File) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *File) GetMode() uint32 {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return 0
}

func (m *File) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *File) GetAction() File_Action {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return File_ADD
}

func init() {
	proto.RegisterType((*File)(nil), "File")
	proto.RegisterEnum("File_Action", File_Action_name, File_Action_value)
}

var fileDescriptor0 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xcb, 0xcc, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xaa, 0xe1, 0x62, 0x71, 0x03, 0xf2, 0x84, 0x78, 0xb8,
	0x58, 0x0a, 0x12, 0x4b, 0x32, 0x24, 0x18, 0x15, 0x98, 0x34, 0x38, 0x41, 0xbc, 0xdc, 0xfc, 0x94,
	0x54, 0x09, 0x26, 0x20, 0x8f, 0x57, 0x88, 0x9f, 0x8b, 0xbd, 0x20, 0xb1, 0x32, 0x27, 0x3f, 0x31,
	0x45, 0x82, 0x19, 0x28, 0xc0, 0x23, 0x24, 0xc3, 0xc5, 0x96, 0x98, 0x5c, 0x92, 0x99, 0x9f, 0x27,
	0xc1, 0x02, 0xe4, 0xf3, 0x19, 0xf1, 0xe8, 0x81, 0xcc, 0xd0, 0x73, 0x04, 0x8b, 0x29, 0x69, 0x72,
	0xb1, 0x41, 0x58, 0x42, 0xec, 0x5c, 0xcc, 0x8e, 0x2e, 0x2e, 0x02, 0x0c, 0x42, 0x5c, 0x5c, 0x6c,
	0xa1, 0x01, 0x2e, 0x8e, 0x21, 0xae, 0x02, 0x8c, 0x20, 0xb6, 0x8b, 0xab, 0x8f, 0x2b, 0x90, 0xcd,
	0x04, 0x08, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x6a, 0xff, 0xb5, 0x8a, 0x00, 0x00, 0x00,
}
